"""Package the Blender export for the offline web viewer: blender/web/scene_data.js
(the .glb as base64 + the statistics, so index.html works from file:// without a server)."""
import base64, json, os
ROOT = os.path.dirname(os.path.abspath(__file__))
glb = open(os.path.join(ROOT, 'out', 'andes_enso.glb'), 'rb').read()
d = json.load(open(os.path.join(ROOT, 'enso3d.json'))); d.pop('terrain')
with open(os.path.join(ROOT, 'web', 'scene_data.js'), 'w') as f:
    f.write('// generated by blender/build_web.py\nwindow.ENSO3D = ' + json.dumps(d, separators=(',', ':'), ensure_ascii=False) + ';\n')
    f.write('window.SCENE_GLB_B64 = "' + base64.b64encode(glb).decode() + '";\n')
print('scene_data.js', os.path.getsize(os.path.join(ROOT, 'web', 'scene_data.js')) // 1024, 'kB')
